# Generated by Django 5.2.4 on 2025-08-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingticket', '0002_flightbooking_trainbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='busbooking',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
