# Generated by Django 5.2.4 on 2025-08-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingticket', '0003_busbooking_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbooking',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trainbooking',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
